export const userData = {
  username: "ofcljaved",
  avatarUrl: "https://avatars.githubusercontent.com/u/66407522?v=4",
  name: "Javed",
  bio: null,
  followers: 75,
  publicRepos: 68,
  totalStars: 30,
};

export const repoData = {
  forkedRepos: [
    {
      name: "photo-ai",
      description: null,
      fork: true,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2025-02-13T05:28:09Z",
      language: null,
      html_url: "https://github.com/ofcljaved/photo-ai",
    },
    {
      name: "gluestack-ui-cli",
      description: "A script to add gluestack/ui to your projects",
      fork: true,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2025-01-29T18:43:46Z",
      language: null,
      html_url: "https://github.com/ofcljaved/gluestack-ui-cli",
    },
    {
      name: "latent-booking",
      description: null,
      fork: true,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2025-01-26T15:32:49Z",
      language: "TypeScript",
      html_url: "https://github.com/ofcljaved/latent-booking",
    },
    {
      name: "chess",
      description: "A multiplayer chess platform similar to https://chess.com/",
      fork: true,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2024-11-06T08:45:38Z",
      language: "TypeScript",
      html_url: "https://github.com/ofcljaved/chess",
    },
    {
      name: "100xdevs-mobile",
      description: null,
      fork: true,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2024-06-29T07:05:51Z",
      language: "TypeScript",
      html_url: "https://github.com/ofcljaved/100xdevs-mobile",
    },
    {
      name: "github-sol-auto-dispenser",
      description:
        "Create a github app that listens to events on a PR and dispenses users funds in crypto. Use the SOL blockchain",
      fork: true,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2024-04-15T06:35:20Z",
      language: null,
      html_url: "https://github.com/ofcljaved/github-sol-auto-dispenser",
    },
    {
      name: "week-17-final-code",
      description: null,
      fork: true,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2024-03-30T13:38:07Z",
      language: null,
      html_url: "https://github.com/ofcljaved/week-17-final-code",
    },
    {
      name: "todo-app",
      description: "A full-stack attempt towards a simple to-do application",
      fork: true,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2024-02-23T16:46:14Z",
      language: "JavaScript",
      html_url: "https://github.com/ofcljaved/todo-app",
    },
    {
      name: "contribute-to-open-source",
      description:
        "[STILL ACTIVE] Learn the GitHub workflow by contributing code in a fun simulation project",
      fork: true,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2023-08-19T15:40:14Z",
      language: "JavaScript",
      html_url: "https://github.com/ofcljaved/contribute-to-open-source",
    },
    {
      name: "apihub",
      description:
        "Your own API Hub to learn and master API interaction. Ideal for frontend, mobile dev and backend developers. ",
      fork: true,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2023-08-19T14:49:37Z",
      language: null,
      html_url: "https://github.com/ofcljaved/apihub",
    },
  ],
  notForkedRepos: [
    {
      name: "system-config",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2025-02-20T11:45:08Z",
      language: "Shell",
      html_url: "https://github.com/ofcljaved/system-config",
    },
    {
      name: "tree",
      description: "To render file structure tree in terminal",
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2025-02-16T17:34:40Z",
      language: "JavaScript",
      html_url: "https://github.com/ofcljaved/tree",
    },
    {
      name: "cricbet",
      description: "Cricket market prediction UI",
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2025-02-16T09:23:55Z",
      language: "TypeScript",
      html_url: "https://github.com/ofcljaved/cricbet",
    },
    {
      name: "gitfork",
      description: "Seperate your forks from main repos",
      fork: false,
      forks_count: 0,
      stargazers_count: 4,
      updated_at: "2025-02-05T04:59:07Z",
      language: "TypeScript",
      html_url: "https://github.com/ofcljaved/gitfork",
    },
    {
      name: "gluestack-theme-fix",
      description: "A minimal setup/fix of system them",
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2025-01-31T12:40:11Z",
      language: "TypeScript",
      html_url: "https://github.com/ofcljaved/gluestack-theme-fix",
    },
    {
      name: "express-vercel",
      description: "Starter project to deploy on vercel",
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2025-01-22T20:39:25Z",
      language: "TypeScript",
      html_url: "https://github.com/ofcljaved/express-vercel",
    },
    {
      name: "with-tailwind",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2025-01-19T12:25:43Z",
      language: "TypeScript",
      html_url: "https://github.com/ofcljaved/with-tailwind",
    },
    {
      name: "remove-element",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2025-01-04T12:53:21Z",
      language: "HTML",
      html_url: "https://github.com/ofcljaved/remove-element",
    },
    {
      name: "learn-go",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2024-12-23T00:08:26Z",
      language: "Go",
      html_url: "https://github.com/ofcljaved/learn-go",
    },
    {
      name: "webrtc",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2024-12-22T00:00:49Z",
      language: "TypeScript",
      html_url: "https://github.com/ofcljaved/webrtc",
    },
    {
      name: "http-server",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2024-12-14T11:52:01Z",
      language: "Rust",
      html_url: "https://github.com/ofcljaved/http-server",
    },
    {
      name: "todo-api",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2024-12-13T16:58:41Z",
      language: "Rust",
      html_url: "https://github.com/ofcljaved/todo-api",
    },
    {
      name: "nvim",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2024-12-13T10:36:03Z",
      language: "Lua",
      html_url: "https://github.com/ofcljaved/nvim",
    },
    {
      name: "cli-todo",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2024-12-12T08:36:06Z",
      language: "Rust",
      html_url: "https://github.com/ofcljaved/cli-todo",
    },
    {
      name: "ofcljaved",
      description: "Config files for my GitHub profile.",
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2024-12-11T02:36:41Z",
      language: null,
      html_url: "https://github.com/ofcljaved/ofcljaved",
    },
    {
      name: "voting",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2024-11-21T19:05:34Z",
      language: "TypeScript",
      html_url: "https://github.com/ofcljaved/voting",
    },
    {
      name: "crud-dapp",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2024-11-15T18:50:40Z",
      language: "TypeScript",
      html_url: "https://github.com/ofcljaved/crud-dapp",
    },
    {
      name: "counter",
      description: "An incremental counter on solana blockchain with anchor",
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2024-11-15T12:51:59Z",
      language: "TypeScript",
      html_url: "https://github.com/ofcljaved/counter",
    },
    {
      name: "learn-rust",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2024-11-10T21:00:54Z",
      language: "Rust",
      html_url: "https://github.com/ofcljaved/learn-rust",
    },
    {
      name: "rustlings",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2024-11-10T18:09:44Z",
      language: "Rust",
      html_url: "https://github.com/ofcljaved/rustlings",
    },
    {
      name: "resource",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2024-08-01T15:03:19Z",
      language: null,
      html_url: "https://github.com/ofcljaved/resource",
    },
    {
      name: "30-days-ts-challenge",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2024-07-29T13:34:21Z",
      language: "TypeScript",
      html_url: "https://github.com/ofcljaved/30-days-ts-challenge",
    },
    {
      name: "doodling",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2024-07-10T03:06:42Z",
      language: "TypeScript",
      html_url: "https://github.com/ofcljaved/doodling",
    },
    {
      name: "testImg",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2024-07-03T18:46:43Z",
      language: "TypeScript",
      html_url: "https://github.com/ofcljaved/testImg",
    },
    {
      name: "multi-step-form",
      description: null,
      fork: false,
      forks_count: 1,
      stargazers_count: 2,
      updated_at: "2024-05-28T12:54:53Z",
      language: "TypeScript",
      html_url: "https://github.com/ofcljaved/multi-step-form",
    },
    {
      name: "electron-app",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2024-05-24T15:12:42Z",
      language: "CSS",
      html_url: "https://github.com/ofcljaved/electron-app",
    },
    {
      name: "wschess",
      description: "Test Web socket for chess app",
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2024-05-13T04:32:29Z",
      language: "TypeScript",
      html_url: "https://github.com/ofcljaved/wschess",
    },
    {
      name: "turbo",
      description: null,
      fork: false,
      forks_count: 1,
      stargazers_count: 1,
      updated_at: "2024-05-06T06:26:14Z",
      language: "CSS",
      html_url: "https://github.com/ofcljaved/turbo",
    },
    {
      name: "notionrecordmap-pdf",
      description: "Library to convert notionrecordmap to pdf",
      fork: false,
      forks_count: 0,
      stargazers_count: 1,
      updated_at: "2024-03-22T05:01:43Z",
      language: "TypeScript",
      html_url: "https://github.com/ofcljaved/notionrecordmap-pdf",
    },
    {
      name: "canvas-skills",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2024-01-04T03:11:05Z",
      language: "TypeScript",
      html_url: "https://github.com/ofcljaved/canvas-skills",
    },
    {
      name: "learn-backend",
      description:
        "Project to learn backend with Hitesh Choudhary and practice it",
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2023-12-30T15:29:38Z",
      language: "TypeScript",
      html_url: "https://github.com/ofcljaved/learn-backend",
    },
    {
      name: "results-summary",
      description: "Frontend Mentor project of results summary component",
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2023-12-13T09:13:00Z",
      language: "CSS",
      html_url: "https://github.com/ofcljaved/results-summary",
    },
    {
      name: "faq-accordion",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2023-12-11T15:23:42Z",
      language: "HTML",
      html_url: "https://github.com/ofcljaved/faq-accordion",
    },
    {
      name: "rich-text-editor",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2023-12-04T16:21:51Z",
      language: "TypeScript",
      html_url: "https://github.com/ofcljaved/rich-text-editor",
    },
    {
      name: "elevate-react-skills",
      description: "Improving my React skills with Hitesh Choudhary",
      fork: false,
      forks_count: 1,
      stargazers_count: 0,
      updated_at: "2023-10-10T05:56:38Z",
      language: "TypeScript",
      html_url: "https://github.com/ofcljaved/elevate-react-skills",
    },
    {
      name: "geonames",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2023-09-23T01:46:24Z",
      language: "JavaScript",
      html_url: "https://github.com/ofcljaved/geonames",
    },
    {
      name: "learn-typescript",
      description: "Project to learn typescript and practice it",
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2023-08-23T15:41:58Z",
      language: "TypeScript",
      html_url: "https://github.com/ofcljaved/learn-typescript",
    },
    {
      name: "weather-bot",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2023-08-16T15:18:02Z",
      language: "JavaScript",
      html_url: "https://github.com/ofcljaved/weather-bot",
    },
    {
      name: "learn-react",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2023-08-09T12:39:38Z",
      language: "JavaScript",
      html_url: "https://github.com/ofcljaved/learn-react",
    },
    {
      name: "browser-css",
      description:
        "A Simple html page where you can write css in the browser with live effects",
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2023-06-08T06:26:30Z",
      language: "HTML",
      html_url: "https://github.com/ofcljaved/browser-css",
    },
    {
      name: "weather-app",
      description: "Project to check weather of any location built with Nextjs",
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2023-05-26T16:39:30Z",
      language: "JavaScript",
      html_url: "https://github.com/ofcljaved/weather-app",
    },
    {
      name: "node_testApi",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2023-05-17T09:21:13Z",
      language: "JavaScript",
      html_url: "https://github.com/ofcljaved/node_testApi",
    },
    {
      name: "QRcode",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2023-02-02T06:47:25Z",
      language: "HTML",
      html_url: "https://github.com/ofcljaved/QRcode",
    },
    {
      name: "Space-tourism",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2022-11-20T14:01:55Z",
      language: "CSS",
      html_url: "https://github.com/ofcljaved/Space-tourism",
    },
    {
      name: "Rating-card",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2022-08-25T12:31:21Z",
      language: "HTML",
      html_url: "https://github.com/ofcljaved/Rating-card",
    },
    {
      name: "Product-card",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2022-08-24T12:19:23Z",
      language: "SCSS",
      html_url: "https://github.com/ofcljaved/Product-card",
    },
    {
      name: "aarons_healthcare",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2022-02-28T16:03:44Z",
      language: "CSS",
      html_url: "https://github.com/ofcljaved/aarons_healthcare",
    },
    {
      name: "freeAdvice",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2022-02-20T15:32:34Z",
      language: "CSS",
      html_url: "https://github.com/ofcljaved/freeAdvice",
    },
    {
      name: "comment-section",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2022-02-05T08:46:02Z",
      language: "HTML",
      html_url: "https://github.com/ofcljaved/comment-section",
    },
    {
      name: "mlnc",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2022-01-25T12:39:09Z",
      language: "CSS",
      html_url: "https://github.com/ofcljaved/mlnc",
    },
    {
      name: "NFT-card",
      description: "Frontend Mentor | NFT preview card component",
      fork: false,
      forks_count: 0,
      stargazers_count: 1,
      updated_at: "2021-12-22T11:12:11Z",
      language: "CSS",
      html_url: "https://github.com/ofcljaved/NFT-card",
    },
    {
      name: "findjaved",
      description: "portfolio of mine",
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2021-08-08T08:05:44Z",
      language: "CSS",
      html_url: "https://github.com/ofcljaved/findjaved",
    },
    {
      name: "tictactoe",
      description: "A game which can play with bot and by yourself too",
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2021-04-10T06:12:15Z",
      language: "JavaScript",
      html_url: "https://github.com/ofcljaved/tictactoe",
    },
    {
      name: "NOTES",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2021-03-26T13:20:43Z",
      language: "CSS",
      html_url: "https://github.com/ofcljaved/NOTES",
    },
    {
      name: "Keep-Clone",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2021-03-25T15:25:25Z",
      language: "HTML",
      html_url: "https://github.com/ofcljaved/Keep-Clone",
    },
    {
      name: "motivation",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2020-10-07T11:49:31Z",
      language: "HTML",
      html_url: "https://github.com/ofcljaved/motivation",
    },
    {
      name: "MUSIC-PLAYER",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2020-09-07T15:49:15Z",
      language: "CSS",
      html_url: "https://github.com/ofcljaved/MUSIC-PLAYER",
    },
    {
      name: "foodietherapy.github.io",
      description: null,
      fork: false,
      forks_count: 0,
      stargazers_count: 0,
      updated_at: "2020-07-23T05:31:13Z",
      language: "HTML",
      html_url: "https://github.com/ofcljaved/foodietherapy.github.io",
    },
  ],
};
